name: Tests

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cppcheck and Valgrind
        run: sudo apt install cppcheck valgrind
      - name: Build
        run: g++ -std=c++17 -o a.out *.cpp
      - name: Gaining rights
        run: chmod a+x ./test.sh ./memtest.sh ./code_analysis.sh
      - name: Calling code analysis
        run: ./code_analysis.sh
      - name: Artifact performance and style messages
        uses: actions/upload-artifact@v2
        with:
          path: ./perf-style_log.txt
      - name: Calling memtest
        run: ./memtest.sh
  
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ -std=c++17 -o a.out *.cpp
      - name: Gaining rights
        run: chmod a+x ./test.sh
      - name: Preventing unwanted output append
        run: rm -f output.csv
      - name: Calling unit-test
        run: ./test.sh
      - name: Checking differences
        run: diff output.csv expected_output.csv
      - name: Deleting temporary file
        run: rm -f output.csv
